name: Dev Ci Test

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
      - main

# 본인이 설정한 값을 여기서 채워넣습니다.
# 리전, 버킷 이름, CodeDeploy 앱 이름, CodeDeploy 배포 그룹 이름.
env:
  AWS_REGION: ap-northeast-2
  S3_BUCKET_NAME: my-github-action-s3-bucket-book
  CODE_DEPLOY_APPLICATION_NAME: my-codedeploy-app
  CODE_DEPLOY_DEPLOYMENT_GROUP_NAME: my-codedeploy-depolyment-group

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      # (1) 기본 체크아웃
      - name: Checkout
        uses: actions/checkout@v3

      # (2) Node.js 세팅
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'

        # (3) build (Test 제외)
      - name: Install dependencies
        run: npm install

      - name: Build test
        run: npm run build

      # - name: run test
      #   run: npm test
